export const CustomTypography = {
  "display-2xl-regular": {
    fontFamily: "Inter",
    fontSize: "72px",
    lineHeight: "90px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "display-2xl-medium": {
    fontFamily: "Inter",
    fontSize: "72px",
    lineHeight: "90px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "display-2xl-semibold": {
    fontFamily: "Inter",
    fontSize: "72px",
    lineHeight: "90px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "display-2xl-bold": {
    fontFamily: "Inter",
    fontSize: "72px",
    lineHeight: "90px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },
  "display-xl-regular": {
    fontFamily: "Inter",
    fontSize: "60px",
    lineHeight: "72px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },

  "display-xl-medium": {
    fontFamily: "Inter",
    fontSize: "60px",
    lineHeight: "72px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "display-xl-semibold": {
    fontFamily: "Inter",
    fontSize: "60px",
    lineHeight: "72px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "display-xl-bold": {
    fontFamily: "Inter",
    fontSize: "60px",
    lineHeight: "72px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },

  "display-lg-regular": {
    fontFamily: "Inter",
    fontSize: "48px",
    lineHeight: "60px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "display-lg-medium": {
    fontFamily: "Inter",
    fontSize: "48px",
    lineHeight: "60px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "display-lg-semibold": {
    fontFamily: "Inter",
    fontSize: "48px",
    lineHeight: "60px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "display-lg-bold": {
    fontFamily: "Inter",
    fontSize: "48px",
    lineHeight: "60px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },
  "display-md-regular": {
    fontFamily: "Inter",
    fontSize: "36px",
    lineHeight: "44px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "display-md-medium": {
    fontFamily: "Inter",
    fontSize: "36px",
    lineHeight: "44px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "display-md-semibold": {
    fontFamily: "Inter",
    fontSize: "36px",
    lineHeight: "44px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "display-md-bold": {
    fontFamily: "Inter",
    fontSize: "36px",
    lineHeight: "44px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },
  "display-sm-regular": {
    fontFamily: "Inter",
    fontSize: "30px",
    lineHeight: "38px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "display-sm-medium": {
    fontFamily: "Inter",
    fontSize: "30px",
    lineHeight: "38px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "display-sm-semibold": {
    fontFamily: "Inter",
    fontSize: "30px",
    lineHeight: "38px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "display-sm-bold": {
    fontFamily: "Inter",
    fontSize: "30px",
    lineHeight: "38px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },

  "display-xs-regular": {
    fontFamily: "Inter",
    fontSize: "24px",
    lineHeight: "32px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "display-xs-medium": {
    fontFamily: "Inter",
    fontSize: "24px",
    lineHeight: "32px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "display-xs-semibold": {
    fontFamily: "Inter",
    fontSize: "24px",
    lineHeight: "32px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "display-xs-bold": {
    fontFamily: "Inter",
    fontSize: "24px",
    lineHeight: "32px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },
  "text-xl-regular": {
    fontFamily: "Inter",
    fontSize: "20px",
    lineHeight: "30px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "text-xl-medium": {
    fontFamily: "Inter",
    fontSize: "20px",
    lineHeight: "30px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "text-xl-semibold": {
    fontFamily: "Inter",
    fontSize: "20px",
    lineHeight: "30px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "text-xl-bold": {
    fontFamily: "Inter",
    fontSize: "20px",
    lineHeight: "30px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },
  "text-lg-regular": {
    fontFamily: "Inter",
    fontSize: "18px",
    lineHeight: "28px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "text-lg-medium": {
    fontFamily: "Inter",
    fontSize: "18px",
    lineHeight: "28px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "text-lg-semibold": {
    fontFamily: "Inter",
    fontSize: "18px",
    lineHeight: "28px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "text-lg-bold": {
    fontFamily: "Inter",
    fontSize: "18px",
    lineHeight: "28px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },
  "text-md-regular": {
    fontFamily: "Inter",
    fontSize: "16px",
    lineHeight: "24px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "text-md-medium": {
    fontFamily: "Inter",
    fontSize: "16px",
    lineHeight: "24px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "text-md-semibold": {
    fontFamily: "Inter",
    fontSize: "16px",
    lineHeight: "24px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "text-md-bold": {
    fontFamily: "Inter",
    fontSize: "16px",
    lineHeight: "24px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },

  "text-sm-regular": {
    fontFamily: "Inter",
    fontSize: "14px",
    lineHeight: "20px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "text-sm-medium": {
    fontFamily: "Inter",
    fontSize: "14px",
    lineHeight: "20px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "text-sm-semibold": {
    fontFamily: "Inter",
    fontSize: "14px",
    lineHeight: "20px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "text-sm-bold": {
    fontFamily: "Inter",
    fontSize: "14px",
    lineHeight: "20px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },
  "text-xs-regular": {
    fontFamily: "Inter",
    fontSize: "12px",
    lineHeight: "28px",
    fontKerning: "0%",
    fontWeight: 400,
    letterSpacing: "",
  },
  "text-xs-medium": {
    fontFamily: "Inter",
    fontSize: "12px",
    lineHeight: "28px",
    fontKerning: "0%",
    fontWeight: 500,
    letterSpacing: "",
  },
  "text-xs-semibold": {
    fontFamily: "Inter",
    fontSize: "12px",
    lineHeight: "28px",
    fontKerning: "0%",
    fontWeight: 600,
    letterSpacing: "",
  },
  "text-xs-bold": {
    fontFamily: "Inter",
    fontSize: "12px",
    lineHeight: "28px",
    fontKerning: "0%",
    fontWeight: 700,
    letterSpacing: "",
  },
};
