import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@mui/material";
import { customTheme } from "@/theme/CustomTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Puller AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={customTheme}>
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
